services:
  librewolf:
    image: lscr.io/linuxserver/librewolf:latest
    container_name: librewolf
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LIBREWOLF_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - /srv/appdata/librewolf/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
