services:
  librewolf:
    image: lscr.io/linuxserver/librewolf:latest
    container_name: librewolf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/appdata/librewolf/config:/config
    ports:
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
